// oetools-image:tag  Docker image from OE Jenkins Registry
OETOOLS_REPO = "https://oejenkinscidockerregistry.azurecr.io"
OETOOLS_REPO_CREDENTIAL_ID = "oejenkinscidockerregistry"
OETOOLS_IMAGE_NAME = "oetools-azure"
OETOOLS_TAG = "1.10"


def PowerShellWrapper(psCmd) {
    psCmd = psCmd.replaceAll("\r", "").replaceAll("\n", "")
    bat "powershell.exe -NonInteractive -ExecutionPolicy Bypass -Command \"\$ErrorActionPreference='Stop';[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;$psCmd;EXIT \$global:LastExitCode\""
}

def ACCTest(String label, String version, String compiler, String unit, String suite) {
    stage("$label $compiler $unit $suite") {
        node("$label") {
            cleanWs()
            checkout scm

            timeout(15) {
                sh "env"
                sh "./scripts/test-build-config -p $unit -b $suite --compiler=$compiler --disable_sim"
            }

        }
    }
}

def simulationTest(String version, String compiler, String unit, String suite ) {
    stage("Sim $compiler $unit $suite") {
        node {
            cleanWs()
            checkout scm

            docker.withRegistry(OETOOLS_REPO, OETOOLS_REPO_CREDENTIAL_ID) {
                docker.image("${OETOOLS_IMAGE_NAME}-${version}:${OETOOLS_TAG}").inside {
                    timeout(15) {
                        sh "./scripts/test-build-config -p $unit -b $suite --compiler=$compiler"
                    }
                }
            }
        }
    }
}

def ACCContainerTest(String label, String version) {
    stage("$label Container RelWithDebInfo") {
        node("$label") {
            cleanWs()
            checkout scm

            docker.withRegistry(OETOOLS_REPO, OETOOLS_REPO_CREDENTIAL_ID) {
                docker.image("${OETOOLS_IMAGE_NAME}-${version}:${OETOOLS_TAG}").inside('--privileged -v /dev/sgx:/dev/sgx') {
                    timeout(15) {
                        sh './scripts/test-build-config -p SGX1FLC -b RelWithDebInfo --disable_sim'
                    }
                }
            }
        }
    }
}

def checkPreCommitRequirements(String version) {
    stage('Check pre-commit requirements') {
        node {
            cleanWs()
            checkout scm

            docker.withRegistry(OETOOLS_REPO, OETOOLS_REPO_CREDENTIAL_ID) {
                docker.image("${OETOOLS_IMAGE_NAME}-${version}:${OETOOLS_TAG}").inside {
                    timeout(2) {
                        sh './scripts/check-ci'
                    }
                }
            }
        }
    }
    stage('Sim default compiler') {
        // This particular test asserts that everything (at least
        // for simulation) can be built after using our
        // install-prereqs ansible playbook to to bootstrap a machine.
        node {
            cleanWs()
            checkout scm

            def buildImage = docker.build("oetools-base", "--build-arg ubuntu_version=$version -f .jenkins/Dockerfile.scripts .")

            buildImage.inside {
                timeout(15) {
                    // This is run to test that it works with the dependencies
                    // installed by our install-prereqs ansible playbook.
                    sh './scripts/check-ci'
                    // installed by our install-prereqs script.

                    dir('build') {
                        sh '''
                        cmake .. -DUSE_LIBSGX=OFF
                        make
                        OE_SIMULATION=1 ctest --verbose --output-on-failure
                    '''
                        // Note that `make package` is not expected to work
                        // without extra configuration.
                    }
                }
            }
        }
    }
}

def win2016DebugCrossPlatform(String version) {
    stage('Linux SGX1 Debug') {
        node {
            cleanWs()
            checkout scm
            docker.withRegistry(OETOOLS_REPO, OETOOLS_REPO_CREDENTIAL_ID) {
                docker.image("${OETOOLS_IMAGE_NAME}-${version}:${OETOOLS_TAG}").inside {
                    timeout(15) {
                        sh './scripts/test-build-config -p SGX1FLC -b Debug --compiler=clang-7'
                        stash includes: 'build/tests/**', name: 'linuxdebug'
                    }
                }
            }
        }
    }
    stage('Windows Debug') {
        node('SGXFLC-Windows') {
            cleanWs()
            checkout scm
            unstash 'linuxdebug'
            PowerShellWrapper('mv build linuxbin')
            PowerShellWrapper('./scripts/test-build-config.ps1 -add_windows_enclave_tests -linux_bin_dir $ENV:WORKSPACE/linuxbin/tests -build_type Debug')
       }
    }
}

def win2016ReleaseCrossPlatform(String version) {
    stage('Linux SGX1 Release') {
        node {
            cleanWs()
            checkout scm
            docker.withRegistry(OETOOLS_REPO, OETOOLS_REPO_CREDENTIAL_ID) {
                docker.image("${OETOOLS_IMAGE_NAME}-${version}:${OETOOLS_TAG}").inside {
                    timeout(15) {
                        sh './scripts/test-build-config -p SGX1FLC -b Release --compiler=clang-7'
                        stash includes: 'build/tests/**', name: 'linuxrelease'
                    }
                }
            }
        }
    }
    stage('Windows Release') {
        node('SGXFLC-Windows') {
            cleanWs()
            checkout scm
            unstash 'linuxrelease'
            PowerShellWrapper('mv build linuxbin')
            PowerShellWrapper('./scripts/test-build-config.ps1 -add_windows_enclave_tests -linux_bin_dir $ENV:WORKSPACE/linuxbin/tests -build_type Release')
        }
    }
}

def win2016Debug() {
    stage('Windows Debug') {
        node('SGXFLC-Windows') {
            cleanWs()
            checkout scm
            PowerShellWrapper('./scripts/test-build-config.ps1 -add_windows_enclave_tests -linux_bin_dir $ENV:WORKSPACE/linuxbin/tests -build_type Debug -build_enclaves')
       }
    }
}

def win2016Release() {
    stage('Windows Release') {
        node('SGXFLC-Windows') {
            cleanWs()
            checkout scm
            PowerShellWrapper('./scripts/test-build-config.ps1 -add_windows_enclave_tests -linux_bin_dir $ENV:WORKSPACE/linuxbin/tests -build_type Release -build_enclaves')
        }
    }
}
parallel "Check Pre-Commit Requirements 1604" :        { checkPreCommitRequirements('16.04') },
         "Sim 1604 clang-7 SGX1 Debug" :               { simulationTest('16.04', 'clang-7', 'SGX1', 'Debug')},
         "Sim 1604 clang-7 SGX1 Release" :             { simulationTest('16.04', 'clang-7', 'SGX1', 'Release')},
         "Sim 1604 clang-7 SGX1 RelWithDebInfo" :      { simulationTest('16.04', 'clang-7', 'SGX1', 'RelWithDebInfo')},
         "Sim 1604 clang-7 SGX1-FLC Debug" :           { simulationTest('16.04', 'clang-7', 'SGX1FLC', 'Debug')},
         "Sim 1604 clang-7 SGX1-FLC Release" :         { simulationTest('16.04', 'clang-7', 'SGX1FLC', 'Release')},
         "Sim 1604 clang-7 SGX1-FLC RelWithDebInfo" :  { simulationTest('16.04', 'clang-7', 'SGX1FLC', 'RelWithDebInfo')},
         "ACC1604 clang-7 Debug" :                     { ACCTest('ACC-1604', '16.04', 'clang-7', 'SGX1FLC', 'Debug') },
         "ACC1604 clang-7 Release" :                   { ACCTest('ACC-1604', '16.04', 'clang-7', 'SGX1FLC', 'Release') },
         "ACC1604 clang-7 RelWithDebInfo" :            { ACCTest('ACC-1604', '16.04', 'clang-7', 'SGX1FLC', 'RelWithDebinfo') },
         "ACC1604 gcc Debug" :                         { ACCTest('ACC-1604', '16.04', 'gcc', 'SGX1FLC', 'Debug') },
         "ACC1604 gcc Release" :                       { ACCTest('ACC-1604', '16.04', 'gcc', 'SGX1FLC', 'Release') },
         "ACC1604 gcc RelWithDebInfo" :                { ACCTest('ACC-1604', '16.04', 'gcc', 'SGX1FLC', 'RelWithDebInfo') },
         "Win2016 Ubuntu1604 Debug Cross-platform" :   { win2016DebugCrossPlatform('16.04') },
         "Win2016 Ubuntu1604 Release Cross-platform" : { win2016ReleaseCrossPlatform('16.04') },
         "ACC1604 Container RelWithDebInfo" :          { ACCContainerTest('ACC-1604', '16.04') },
         "Check Pre-Commit Requirements 1804" :        { checkPreCommitRequirements('18.04') },
         "Sim 1804 clang-7 SGX1 Debug" :               { simulationTest('18.04', 'clang-7', 'SGX1', 'Debug')},
         "Sim 1804 clang-7 SGX1 Release" :             { simulationTest('18.04', 'clang-7', 'SGX1', 'Release')},
         "Sim 1804 clang-7 SGX1 RelWithDebInfo" :      { simulationTest('18.04', 'clang-7', 'SGX1', 'RelWithDebInfo')},
         "Sim 1804 clang-7 SGX1-FLC Debug" :           { simulationTest('18.04', 'clang-7', 'SGX1FLC', 'Debug')},
         "Sim 1804 clang-7 SGX1-FLC Release" :         { simulationTest('18.04', 'clang-7', 'SGX1FLC', 'Release')},
         "Sim 1804 clang-7 SGX1-FLC RelWithDebInfo" :  { simulationTest('18.04', 'clang-7', 'SGX1FLC', 'RelWithDebInfo')},
         "ACC1804 clang-7 Debug" :                     { ACCTest('ACC-1804', '18.04', 'clang-7', 'SGX1FLC', 'Debug') },
         "ACC1804 clang-7 Release" :                   { ACCTest('ACC-1804', '18.04', 'clang-7', 'SGX1FLC', 'Release') },
         "ACC1804 clang-7 RelWithDebInfo" :            { ACCTest('ACC-1804', '18.04', 'clang-7', 'SGX1FLC', 'RelWithDebinfo') },
         "ACC1804 gcc Debug" :                         { ACCTest('ACC-1804', '18.04', 'gcc', 'SGX1FLC', 'Debug') },
         "ACC1804 gcc Release" :                       { ACCTest('ACC-1804', '18.04', 'gcc', 'SGX1FLC', 'Release') },
         "ACC1804 gcc RelWithDebInfo" :                { ACCTest('ACC-1804', '18.04', 'gcc', 'SGX1FLC', 'RelWithDebInfo') },
         "Win2016 Ubuntu1804 Debug Cross-platform" :   { win2016DebugCrossPlatform('18.04') },
         "Win2016 Ubuntu1804 Release Cross-platform" : { win2016ReleaseCrossPlatform('18.04') },
         "ACC1804 Container RelWithDebInfo" :          { ACCContainerTest('ACC-1804', '18.04') }
